version: '2.4'

services:
  authentication-api:
    image: authentication-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authentication-api
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: change-me-in-prod
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      GOOGLE_CLIENT_ID: ""
      GOOGLE_CLIENT_SECRET: ""
      FACEBOOK_CLIENT_ID: ""
      FACEBOOK_CLIENT_SECRET: ""
      FRONTEND_URL: http://localhost:3000
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
    ports:
      - "8081:8080"
      - "8000:8000"
    networks:
      - mysql-network


volumes:
  app_data:
